name: Push Storybook Branches to Forked Repo

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'
      - 'refactor/*'

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Prepare full project copy into output/
        shell: bash
        run: |
          echo "📁 Copying full project (excluding .git, output, etc)"
          mkdir -p output
          shopt -s dotglob extglob
          cp -r !(output|.git) output/
          rm -rf output/.git

      - name: Copy .github from fork repo (preserve workflows)
        env:
          TOKEN: ${{ secrets.FORKED_REPO_KEY }}
        run: |
          echo "🔁 Cloning forked repo branch: ${{ github.ref_name }}"
          git clone --depth=1 --branch ${{ github.ref_name }} https://x-access-token:$TOKEN@github.com/nninyeong/ormee_web.git fork

          echo "🛠 Replacing .github with fork's version"
          rm -rf output/.github
          cp -r fork/.github output/.github || echo "⚠️ No .github in fork repo yet"

      - name: Push to forked repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORKED_REPO_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'nninyeong'
          destination-repository-name: 'ormee_web'
          user-email: ${{ secrets.DEPLOY_EMAIL }}
          commit-message: '[storybook] sync ${{ github.ref_name }} to fork'
          target-branch: ${{ github.ref_name }}
          create-target-branch-if-needed: true
