name: Push Storybook Branches to Forked Repo

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'
      - 'refactor/*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare output
        run: |
          mkdir -p output
          sh ./build.sh
          cp -r .storybook output/.storybook
          cp -r components output/components
          cp -r lib output/lib

      - name: Clone fork repo and copy .github
        env:
          TOKEN: ${{ secrets.FORKED_REPO_KEY }}
        run: |
          git clone --depth=1 --branch ${{ github.ref_name }} https://x-access-token:$TOKEN@github.com/nninyeong/ormee_web.git fork-repo
          cp -r fork-repo/.github output/.github

      - name: Push to forked repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORKED_REPO_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'nninyeong'
          destination-repository-name: 'ormee_web'
          user-email: ${{ secrets.DEPLOY_EMAIL }}
          commit-message: '[storybook] sync ${{ github.ref_name }} to fork'
          target-branch: ${{ github.ref_name }}
          create-target-branch-if-needed: true
