name: Push Storybook Branches to Forked Repo

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'
      - 'refactor/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare output
        run: |
          mkdir -p output
          sh ./build.sh
          cp -r .storybook output/.storybook

      - name: Push to forked repo (same branch)
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORKED_REPO_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'nninyeong'
          destination-repository-name: 'ormee_web'
          user-email: ${{ secrets.DEPLOY_EMAIL }}
          commit-message: '[storybook] sync ${{ github.ref_name }} to fork'
          target-branch: ${{ github.ref_name }}
          create-target-branch-if-needed: true
