name: Push Storybook Branches to Forked Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  storybook-test:
    name: ✅ Run Storybook Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Run Storybook tests
        run: pnpm test-storybook

  sync-to-fork:
    name: 🚀 Sync to Forked Repo
    runs-on: ubuntu-latest
    needs: storybook-test # ✅ 테스트 통과 시에만 실행됨

    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Prepare output directory
        shell: bash
        run: |
          echo "📦 Copying full project to output/"
          mkdir -p output
          shopt -s dotglob extglob
          cp -r !(output|.git) output/
          rm -rf output/.git

      - name: Copy .github from fork repo (preserve workflows)
        env:
          TOKEN: ${{ secrets.FORKED_REPO_KEY }}
        run: |
          echo "🔁 Cloning forked branch: ${{ github.ref_name }}"
          git clone --depth=1 --branch ${{ github.ref_name }} https://x-access-token:$TOKEN@github.com/nninyeong/ormee_web.git fork

          echo "🔧 Replacing .github with fork's version"
          rm -rf output/.github
          cp -r fork/.github output/.github || echo "⚠️ No .github found in fork (first push?)"

      - name: Push to forked repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORKED_REPO_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'nninyeong'
          destination-repository-name: 'ormee_web'
          user-email: ${{ secrets.DEPLOY_EMAIL }}
          commit-message: '[storybook] sync ${{ github.ref_name }} to fork'
          target-branch: ${{ github.ref_name }}
          create-target-branch-if-needed: true
