name: PR Build & Storybook Test Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: 🛠️ Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1️⃣ 코드 체크아웃
      - uses: actions/checkout@v3

      # 2️⃣ pnpm 설치
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 3️⃣ Node.js 환경 설정
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4️⃣ 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # 5️⃣ Next.js 빌드 실행
      - name: Build Next.js
        id: nextbuild
        run: |
          set -o pipefail
          pnpm build 2>&1 | tee next-build.log

      # 6️⃣ Storybook 정적 빌드
      - name: Build Storybook
        id: sbbuild
        run: |
          set -o pipefail
          pnpm build-storybook 2>&1 | tee sb-build.log

      # 7️⃣ Storybook 서버 실행 (백그라운드) 및 대기
      - name: Start Storybook server
        run: |
          pnpm dlx wait-on http://127.0.0.1:6006 &
          pnpm start-storybook --ci --quiet -p 6006 &

      # 8️⃣ Storybook 테스트 실행
      - name: Test Storybook
        id: sbtest
        run: |
          pnpm dlx wait-on http://127.0.0.1:6006
          pnpm test-storybook 2>&1 | tee sb-test.log

      # 9️⃣ 실패 요약 추출
      - name: Extract error summary
        id: error
        if: failure()
        run: |
          echo "📋 Extracting error summary from logs..."
          tail -n 50 next-build.log > error-next.log || true
          tail -n 50 sb-build.log > error-sb.log || true
          tail -n 50 sb-test.log > error-sbtest.log || true

          SUMMARY=$( (grep -i -E "error|failed|unexpected|cannot|not found" error-next.log || true; \
                      grep -i -E "error|failed|unexpected|cannot|not found" error-sb.log || true; \
                      grep -i -E "error|failed|unexpected|cannot|not found" error-sbtest.log || true) | tail -n 15 | sed 's/^/> /')
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  comment:
    name: 💬 PR 결과 요약 댓글
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: build-status
          message: |
            ### 🧪 **PR 빌드 및 Storybook 테스트 결과**

            - 🏗️ **Next.js Build**: ${{ needs.build.result == 'success' && '✅ 성공' || '❌ 실패' }}
            - 📦 **Storybook Build**: ${{ needs.build.result == 'success' && '✅ 성공' || '❌ 실패' }}
            - 🔬 **Storybook Test**: ${{ needs.build.result == 'success' && '✅ 성공' || '❌ 실패' }}

            ${{ needs.build.result == 'failure' && format(
              '🧾 **에러 요약**:\n\n```\n{0}\n```',
              steps.error.outputs.summary
            ) }}

            로컬에서 재현하려면 다음 명령어를 실행하세요:

            ```bash
            pnpm install
            pnpm build
            pnpm build-storybook
            pnpm storybook
            pnpm test-storybook
            ```
