name: Comment Storybook Preview on PR

on:
  repository_dispatch:
    types: [storybook_deploy_detected]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Extract dispatch payload
        id: input
        run: |
          echo "branch=${{ github.event.client_payload.branch }}" >> $GITHUB_OUTPUT
          echo "url=${{ github.event.client_payload.url }}" >> $GITHUB_OUTPUT
          echo "state=${{ github.event.client_payload.state }}" >> $GITHUB_OUTPUT

      - name: Find PR number from branch
        id: pr
        run: |
          BRANCH=${{ steps.input.outputs.branch }}

          echo "🔍 Searching for open PR from branch: $BRANCH"

          PR_API="https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:$BRANCH"
          echo "🔗 $PR_API"

          PR_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$PR_API")
          PR_NUMBER=$(echo "$PR_RESPONSE" | jq '.[0].number')

          if [ "$PR_NUMBER" = "null" ] || [ -z "$PR_NUMBER" ]; then
            echo "❌ No open PR found for branch: $BRANCH"
            echo "pr_number=" >> $GITHUB_OUTPUT
          else
            echo "✅ Found PR number: $PR_NUMBER"
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR with preview URL
        if: ${{ steps.pr.outputs.pr_number != '' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: storybook-preview
          number: ${{ steps.pr.outputs.pr_number }}
          message: |
            🚀 **Storybook Preview**
            🔗 [미리보기 열기](${{ steps.input.outputs.url }})
            🟡 상태: `${{ steps.input.outputs.state }}`

            _미리보기 링크는 브랜치가 업데이트되면 자동으로 최신 상태로 교체됩니다._
