name: PR Storybook Preview Link via Vercel API

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT

      - name: Query Vercel for latest READY preview deployment
        id: vercel
        run: |
          BRANCH=${{ steps.get_branch.outputs.branch }}
          echo "🔍 Looking for preview deployment of branch: $BRANCH"

          ATTEMPTS=5
          INTERVAL=5
          FOUND=""

          for ((i = 1; i <= $ATTEMPTS; i++)); do
            echo "⏱️ Attempt $i/$ATTEMPTS..."

            RESPONSE=$(curl -s -G "https://api.vercel.com/v6/deployments" \
              --data-urlencode "projectId=${{ secrets.VERCEL_PROJECT_ID }}" \
              --data-urlencode "meta.githubCommitRef=$BRANCH" \
              --data-urlencode "target=preview" \
              -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}")

            echo "$RESPONSE" > vercel_response.json

            URL=$(jq -r '.deployments[] | select(.state == "READY") | .url' < vercel_response.json | head -n 1)

            if [ "$URL" != "" ]; then
              FOUND=$URL
              echo "✅ Found READY deployment: $URL"
              break
            else
              echo "🕓 Deployment not ready yet. Waiting..."
              sleep $INTERVAL
            fi
          done

          if [ "$FOUND" = "" ]; then
            echo "❌ No READY preview deployment found for branch $BRANCH"
            echo "preview_url=" >> $GITHUB_OUTPUT
          else
            echo "preview_url=https://$FOUND" >> $GITHUB_OUTPUT
          fi

      - name: Post Storybook Preview comment
        if: ${{ steps.vercel.outputs.preview_url != '' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: storybook-preview
          message: |
            🚀 **Storybook Preview**
            🔗 ${{ steps.vercel.outputs.preview_url }}
