name: Comment Storybook Preview on PR

on:
  repository_dispatch:
    types: [storybook_preview_ready]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract values from dispatch
        id: input
        run: |
          echo "branch=${{ github.event.client_payload.branch }}" >> $GITHUB_OUTPUT
          echo "url=${{ github.event.client_payload.url }}" >> $GITHUB_OUTPUT
          echo "state=${{ github.event.client_payload.state }}" >> $GITHUB_OUTPUT

      - name: Comment on PR with preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: storybook-preview
          message: |
            🚀 **Storybook Preview**
            🔗 [${{ steps.input.outputs.url }}](${{ steps.input.outputs.url }})
            🟡 상태: `${{ steps.input.outputs.state }}`
